version: "3.9"
services:
    mysql:
        image: mysql:latest
        container_name: db_mysql
        working_dir: /application
        volumes:
            - ./database:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - 3306:3306

    webserver:
        image: nginx:latest
        container_name: webserver_nginx
        working_dir: /application
        volumes:
            - .:/application
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./logs:/var/log
        ports:
            - 80:80

    php-fpm:
        build: docker/php-fpm
        container_name: php_fpm
        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
        environment:
            -  DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}?serverVersion=5.7

    
    phpmyadmin:
        container_name: phpMyAdmin
        depends_on:
            - mysql
        image: phpmyadmin:latest
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: mysql
